@baseUrl = http://localhost:3000
@model = api/movies
@customId = 60a134ab0e77fd5dcfaf92ac

### ReadAll
GET {{ baseUrl }}/{{model}} HTTP/1.1

### ReadOne
GET {{ baseUrl }}/{{model}}/{{ getPost.response.body._id }} HTTP/1.1

### ReadOne Custom
GET {{ baseUrl }}/{{model}}/{{customId}} HTTP/1.1

### Create
# @name getPost
POST {{ baseUrl }}/{{model}} HTTP/1.1
Content-Type: application/json

{
    "title": "Terminator",
    "genreId": "60a06dae9cb8b339eba33c1d",
    "numberInStock": "3",
    "dailyRentalRate": "2"
}

### Update
PUT {{ baseUrl }}/{{model}}/{{ getPost.response.body._id }} HTTP/1.1
Content-Type: application/json

{
    "title": "Terminator2",
    "genreId": "60a06dcd9cb8b339eba33c1e",
    "numberInStock": "2",
    "dailyRentalRate": "2"
}

### Delete
DELETE {{ baseUrl }}/{{model}}/{{ getPost.response.body._id }} HTTP/1.1

### Delete Custom
DELETE {{ baseUrl }}/{{model}}/{{customId}} HTTP/1.1