@baseUrl = http://localhost:3000
@model = api/rentals
@customId = 60a176acb7378870223261da

### ReadAll
GET {{ baseUrl }}/{{model}} HTTP/1.1

### ReadOne
GET {{ baseUrl }}/{{model}}/{{ getPost.response.body._id }} HTTP/1.1

### ReadOne Custom
GET {{ baseUrl }}/{{model}}/{{customId}} HTTP/1.1

### Create
# @name getPost
POST {{ baseUrl }}/{{model}} HTTP/1.1
Content-Type: application/json

{
    "customerId": "60a0e5c809fe9646a9eae06b",
    "movieId": "60a134a80e77fd5dcfaf92a8"
}

### Update
PUT {{ baseUrl }}/{{model}}/{{ getPost.response.body._id }} HTTP/1.1
Content-Type: application/json

{
    "customerId": "60a0e5c809fe9646a9eae06b",
    "movieId": "60a06dae9cb8b339eba33c1d"
}

### Delete
DELETE {{ baseUrl }}/{{model}}/{{ getPost.response.body._id }} HTTP/1.1

### Delete Custom
DELETE {{ baseUrl }}/{{model}}/{{customId}} HTTP/1.1