@baseUrl = http://localhost:3000
@genres = api/genres
@customId = 60a0700aae18693b13a8d865

### ReadAll
GET {{ baseUrl }}/{{genres}} HTTP/1.1

### ReadOne
GET {{ baseUrl }}/{{genres}}/{{ getPost.response.body._id }} HTTP/1.1

### Create
# @name getPost
POST {{ baseUrl }}/{{genres}} HTTP/1.1
Content-Type: application/json

{
    "name": "Horror"
}

### Update
PUT {{ baseUrl }}/{{genres}}/{{ getPost.response.body._id }} HTTP/1.1
Content-Type: application/json

{
    "name": "Action"
}

### Delete
DELETE {{ baseUrl }}/{{genres}}/{{ getPost.response.body._id }} HTTP/1.1

### Delete Custom
DELETE {{ baseUrl }}/{{genres}}/{{customId}} HTTP/1.1